name: CICD

on:
  push:
    branches: [deploy-to-ec2]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: login to docker hub
        run: echo ${{secrets.DOCKER_HUB_ACCESS_TOKEN}} | docker login -u ${{secrets.DOCKER_HUB}} --password-stdin
      - name: Build docker image
        run: docker build -t casseli/springbackendprod .
      - name: Publish image to docker hub
        run: docker push casseli/springbackendprod:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull imagen from docker hub
        run: docker pull casseli/springbackendprod:latest
      - name: Delete old container
        run: docker rm -f springbackendprod-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name springbackendprod-container casseli/springbackendprod
